config/routes.rb
Rails.application.routes.draw do

  resources :videos
  resources :services
  resources :categories, except: :show
  
  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :description, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  
  validates :name, :description, :logo, :category_id, presence: true
  
  has_attached_file :logo, styles: { thumb: "100x100>"}
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :service
  
  validates :title, :description, :wistia_id, :service_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order('name ASC')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.order('name ASC')
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:category_id, :name, :description, :logo)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :wistia_id, :service_id, :transcript, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error-explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/layouts/_alert.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Documentation", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Documentation</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container">
    <%= render 'layouts/alert' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Setup any web app you want</h1>
<h2>No tech documentation. Easy installation tutorials.</h2>

<br>

<% @categories.each do |category| %>
  <h2><%= category.name %>    
    <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-trigger="focus" tabindex="0" 
                data-content="<%= category.description %>"></span>
  </h2>
  
  
  <div class="row">
    <% Service.where(category_id: category.id).each do |service| %>
      <div class="col-md-4">
        <h3>
          <%= image_tag service.logo.url(:thumb) %>
        </h3>

        <p><%= service.description %></p>
        
        <% if Video.where(service_id: service.id).length > 0 %>
          <%= link_to "View video guide", videos_path, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "No videos...yet", '#', class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
  
<% end %>

app/views/services/_form.html.erb
<%= form_for @service, html: { multipart: true } do |f| %>
  <% if @service.errors.any? %>
    <div id="error-explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h4>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>
  <div class="form-group">
    <%#= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" },
        {class: "btn btn-default btn-lg dropdown-toggle"} %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Services, Tools, and APIs</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Category</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= image_tag service.logo.url(:thumb) %></td>
        <td><%= service.category.name %></td>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>Add a new service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<%= image_tag @service.logo.url(:thumb) %>

<p>
  <strong>Category:</strong>
  <%= @service.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error-explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h4>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%#= f.label :service_id %>
    <%= f.collection_select :service_id, Service.order('name ASC'), :id, :name, { prompt: "Choose a service" },
        {class: "btn btn-default btn-lg dropdown-toggle"} %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Wistia Embed ID" %>
    <%= f.text_field :wistia_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :transcript %>
    <%= f.text_area :transcript, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<% @videos.each do |video| %>
  
  <h2><%= "#{video.service.name}: #{video.title}" %></h2>
  <p><%= video.description %></p>
  
  <div id="<%= "wistia_#{video.wistia_id}" %>" class="wistia_embed" style="width:640px;height:360px;"></div>
  <script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js"></script>
  <script>
    wistiaEmbed = Wistia.embed("sk3fo15obd");
  </script>
  
  <br>
  
  <div class="panel panel-default">
    <div class="panel-body">
  
      <!-- Nav tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><%= link_to "Transcript", "#transcript", :'data-toggle' => "tab" %></li>
        <li><%= link_to "Notes", "#notes", :'data-toggle' => "tab" %></li>
        <li><%= link_to "Discussion", "#discussion", :'data-toggle' => "tab" %></li>
      </ul>
      
      <br>

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane fade in active" id="transcript">
          <div class="transcript">
            <% unless video.transcript.blank? %>
              <%= video.transcript %>
              <%#= raw textilize(coderay(@video.try(:transcript))) %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="notes">
          <div class="notes">
            <% unless video.notes.blank? %>
              <%= video.notes %>
              <%#= raw textilize(coderay(@video.try(:notes))) %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="discussion">

          <!-- Display comment form -->
          <div class="comment-form">
            <h4>Post a comment</h4>
            <%#= render partial: 'comments/form', locals: { comment: @new_comment, parent_id: nil } %>
          </div>

          <!-- Display all comments -->
          <%#= render partial: 'comments/comment', collection: @comments, as: :comment,
              locals: { new_comment: @new_comment } %>

        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/videos/new.html.erb
<h1>Add a new video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div id="<%= "wistia_#{@video.wistia_id}" %>" class="wistia_embed" style="width:640px;height:360px;"></div>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js"></script>
<script>
  wistiaEmbed = Wistia.embed("sk3fo15obd");
</script>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Service:</strong>
  <%= @video.service.name %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>